const predefinedQuestions = [
  { question: "What is the return policy?", answer: "You can return items within 30 days of purchase." },
  { question: "What payment methods do you accept?", answer: "We accept payments via Stripe, PayPal, and credit cards." },
  { question: "How long does shipping take?", answer: "Shipping takes 5-7 business days." },
  { question: "Do you ship internationally?", answer: "Yes, we ship internationally." },
  { question: "Can I track my order?", answer: "Yes, you can track your order using the tracking number sent to your email." },
  { question: "What sizes do you offer?", answer: "We offer sizes ranging from 6 to 13 for men and women." },
  { question: "Are your shoes eco-friendly?", answer: "Yes, many of our shoes are made with sustainable materials." },
  { question: "Do you offer discounts?", answer: "We have seasonal discounts and offer promotional codes from time to time." },
  { question: "How can I contact customer service?", answer: "You can contact us via email at support@shoestore.com or call us at 1-800-SHOES." },
  { question: "Can I cancel my order?", answer: "Yes, you can cancel your order within 24 hours of placing it." },
  { question: "How do I change my shipping address?", answer: "You can change your shipping address by contacting our support team." },
  { question: "What is your exchange policy?", answer: "We offer exchanges within 30 days for unused products." },
  { question: "Can I modify my order?", answer: "You can modify your order by contacting us before it ships." },
  { question: "How do I know if a shoe is in stock?", answer: "Our website will show stock availability on the product page." },
  { question: "Do you offer gift cards?", answer: "Yes, we offer digital gift cards in various amounts." },
  { question: "How can I clean my sneakers?", answer: "We recommend using a damp cloth and gentle soap to clean your sneakers." },
  { question: "Are your shoes true to size?", answer: "Most of our shoes run true to size, but check the product description for specific details." },
  { question: "What brands do you carry?", answer: "We carry popular brands like Nike, Adidas, Puma, and more." },
  { question: "Can I buy shoes in bulk?", answer: "Yes, we offer bulk purchasing for certain models. Contact us for more information." },
  { question: "How do I apply a coupon?", answer: "You can apply a coupon during the checkout process." },
  { question: "What is the warranty on your shoes?", answer: "We offer a 1-year warranty on all of our shoes." },
  { question: "How do I create an account?", answer: "You can create an account by clicking on 'Sign Up' on our homepage." },
  { question: "Can I shop without creating an account?", answer: "Yes, you can checkout as a guest." },
  { question: "Do you offer free shipping?", answer: "We offer free shipping on orders over $50." },
  { question: "What is the fastest way to get my order?", answer: "We offer express shipping options at checkout for an additional fee." },
  { question: "How do I reset my password?", answer: "Click on 'Forgot Password' on the login page to reset your password." },
  { question: "How do I know if my order has been placed?", answer: "You will receive a confirmation email once your order is placed." },
  { question: "What materials are your shoes made of?", answer: "Our shoes are made of high-quality leather, mesh, and synthetic materials." },
  { question: "Can I return a sale item?", answer: "Yes, sale items can be returned within 30 days." }
];

module.exports = predefinedQuestions;
